export interface SiteItem {
  id: string;
  name: string;
  domain: string;
  url: string;
  category: string;
  icon: string;
  tags: string[];
  uptime: string;
  rating: string;
  badge?: string;
  description: string;
}

export const STREAMING_SITES: SiteItem[] = [
  {
    id: "flixtor",
    name: "Flixtor HD",
    domain: "flixtor.to",
    url: "https://flixtor.to",
    category: "Movies",
    icon: "🍿",
    tags: ["4K", "No-Ads", "Fast Player"],
    uptime: "99.9%",
    rating: "4.9 ★",
    badge: "POPULAR",
    description: "Ultra-fast movie & series streaming with zero popups and 4K playback.",
  },
  {
    id: "aniwave",
    name: "AniWave Anime",
    domain: "aniwave.to",
    url: "https://aniwave.to",
    category: "Anime",
    icon: "🍥",
    tags: ["Dubbed", "Subbed", "HD"],
    uptime: "99.8%",
    rating: "4.9 ★",
    badge: "TOP ANIME",
    description: "Massive anime collection with fast servers, dual audio, and automatic episode auto-play.",
  },
  {
    id: "hdtoday",
    name: "HDToday TV",
    domain: "hdtoday.tv",
    url: "https://hdtoday.tv",
    category: "Series",
    icon: "📺",
    tags: ["Series", "1080p", "Auto-Next"],
    uptime: "99.7%",
    rating: "4.8 ★",
    description: "Stream latest TV series, web shows and trending blockbusters in high quality.",
  },
  {
    id: "streameast",
    name: "StreamEast Sports",
    domain: "streameast.app",
    url: "https://streameast.app",
    category: "Sports",
    icon: "⚽",
    tags: ["Live Sports", "Football", "NBA"],
    uptime: "99.9%",
    rating: "5.0 ★",
    badge: "LIVE 24/7",
    description: "Premier live sports streaming for Football, Basketball, UFC, F1, and Cricket.",
  },
  {
    id: "chatgpt",
    name: "ChatGPT AI Hub",
    domain: "chatgpt.com",
    url: "https://chatgpt.com",
    category: "AI & Tools",
    icon: "🤖",
    tags: ["GPT-4o", "AI Tool", "Free"],
    uptime: "99.9%",
    rating: "5.0 ★",
    badge: "HOT AI",
    description: "Advanced AI conversational assistant for writing, coding, analysis, and productivity.",
  },
  {
    id: "fmovies",
    name: "FMovies Official",
    domain: "fmovies.to",
    url: "https://fmovies.to",
    category: "Movies",
    icon: "🍿",
    tags: ["Movies", "HD", "Multi-Server"],
    uptime: "99.6%",
    rating: "4.7 ★",
    description: "Huge catalog of Hollywood releases, cinema movies, and multi-language subtitles.",
  },
  {
    id: "hianime",
    name: "HiAnime Stream",
    domain: "hianime.to",
    url: "https://hianime.to",
    category: "Anime",
    icon: "🍥",
    tags: ["Uncensored", "60FPS", "Anime"],
    uptime: "99.9%",
    rating: "4.9 ★",
    badge: "TRENDING",
    description: "Smooth 60FPS anime streaming portal with zero lag and instant load speeds.",
  },
  {
    id: "soap2day",
    name: "Soap2Day HD",
    domain: "soap2day.rs",
    url: "https://soap2day.rs",
    category: "Movies",
    icon: "🎬",
    tags: ["Free", "Cinema", "Subtitles"],
    uptime: "99.5%",
    rating: "4.6 ★",
    description: "Classic movie directory featuring timeless films, documentaries, and daily updates.",
  },
  {
    id: "viprow",
    name: "VipRow Sports",
    domain: "viprow.nu",
    url: "https://viprow.nu",
    category: "Sports",
    icon: "🏆",
    tags: ["WWE", "Boxing", "Football"],
    uptime: "99.8%",
    rating: "4.8 ★",
    description: "Comprehensive live sports portal with links to Tennis, Golf, Racing, and Combat sports.",
  },
  {
    id: "claudeai",
    name: "Claude AI Studio",
    domain: "claude.ai",
    url: "https://claude.ai",
    category: "AI & Tools",
    icon: "🧠",
    tags: ["Sonnet 3.5", "AI Assistant"],
    uptime: "99.9%",
    rating: "4.9 ★",
    badge: "PRO AI",
    description: "State of the art AI model by Anthropic for deep reasoning, coding, and document analysis.",
  },
  {
    id: "twitch",
    name: "Twitch 24/7 Live",
    domain: "twitch.tv",
    url: "https://twitch.tv",
    category: "Live Streams",
    icon: "👾",
    tags: ["Live", "Gaming", "IRL"],
    uptime: "100%",
    rating: "5.0 ★",
    badge: "LIVE 24/7",
    description: "World's largest live streaming platform for gamers, music, esports, and creators.",
  },
  {
    id: "9anime",
    name: "9Anime Portal",
    domain: "9anime.se",
    url: "https://9anime.se",
    category: "Anime",
    icon: "🍥",
    tags: ["Fast", "Full-HD", "Dubbed"],
    uptime: "99.7%",
    rating: "4.8 ★",
    description: "High quality anime episodes with multi-language subtitle customization.",
  },
];
